"""create tables

Revision ID: dd1bc16791e5
Revises: 
Create Date: 2023-12-21 08:15:30.161853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd1bc16791e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ルームID'),
    sa.Column('room_name', sa.String(length=256), nullable=False, comment='ルーム名'),
    sa.Column('description', sa.Text(), nullable=False, comment='ルームの説明'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日時※メッセージが投稿されるたびアップデートする'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='削除日時'),
    sa.PrimaryKeyConstraint('id'),
    comment='ルームモデル',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ユーザーID'),
    sa.Column('email', sa.String(length=256), nullable=False, comment='メールアドレス'),
    sa.Column('password', sa.Text(), nullable=False, comment='パスワード'),
    sa.Column('username', sa.Text(), nullable=False, comment='ユーザー名'),
    sa.Column('zipcode', sa.String(length=8), nullable=True, comment='郵便番号'),
    sa.Column('address', sa.Text(), nullable=True, comment='住所'),
    sa.Column('phone_number', sa.String(length=16), nullable=True, comment='電話番号'),
    sa.Column('gender', sa.Integer(), nullable=False, comment='性別'),
    sa.Column('token', sa.String(length=256), nullable=True, comment='何かしらのランダム性を持った文字列'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='ユーザー登録日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='ユーザー更新日時'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='ユーザー削除日時'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token'),
    comment='ユーザーモデル',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='メッセージID'),
    sa.Column('message', sa.Text(), nullable=False, comment='メッセージ'),
    sa.Column('room_id', sa.Integer(), nullable=False, comment='ルームID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('deleted_at', sa.DateTime(), nullable=False, comment='削除日時'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='メッセージモデル',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='参加者ID'),
    sa.Column('room_id', sa.Integer(), nullable=False, comment='ルームID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='unique_room_id_user_id'),
    comment='参加者モデル',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('message_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='メッセージID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('message_id', sa.Integer(), nullable=False, comment='メッセージID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='いいねした日時'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='いいねを取り消した日時'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'message_id', name='unique_user_id_message_id'),
    comment='メッセージモデル',
    mysql_collate='utf8_general_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_likes')
    op.drop_table('participants')
    op.drop_table('messages')
    op.drop_table('users')
    op.drop_table('rooms')
    # ### end Alembic commands ###
