"""create tables

Revision ID: 8c571aed9706
Revises: 9525050c04f1
Create Date: 2023-11-03 00:11:08.014928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c571aed9706'
down_revision: Union[str, None] = '9525050c04f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('room_id', sa.Integer(), nullable=False, comment='ルームID'))
    op.add_column('messages', sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID'))
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'user_id')
    op.drop_column('messages', 'room_id')
    # ### end Alembic commands ###
