"""create tables

Revision ID: 9525050c04f1
Revises: 
Create Date: 2023-11-02 23:53:04.137535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9525050c04f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='メッセージID'),
    sa.Column('message', sa.Text(), nullable=False, comment='メッセージ'),
    sa.PrimaryKeyConstraint('id'),
    comment='メッセージモデル',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ルームID'),
    sa.Column('room_name', sa.Text(), nullable=False, comment='ルーム名'),
    sa.Column('description', sa.Text(), nullable=False, comment='ルームの説明'),
    sa.PrimaryKeyConstraint('id'),
    comment='ルームモデル',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ユーザーID'),
    sa.Column('email', sa.Text(), nullable=False, comment='メールアドレス'),
    sa.Column('password', sa.Text(), nullable=False, comment='パスワード'),
    sa.Column('username', sa.Text(), nullable=False, comment='ユーザー名'),
    sa.Column('gender', sa.Integer(), nullable=False, comment='性別'),
    sa.PrimaryKeyConstraint('id'),
    comment='ユーザーモデル',
    mysql_collate='utf8_general_ci'
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='参加者ID'),
    sa.Column('room_id', sa.Integer(), nullable=False, comment='ルームID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='参加者モデル',
    mysql_collate='utf8_general_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    op.drop_table('users')
    op.drop_table('rooms')
    op.drop_table('messages')
    # ### end Alembic commands ###
